# Generated by Django 3.0.8 on 2020-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sospet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='pet'),
        ),
    ]
